version: '3.8'
services:
  backend:
    build: ../backend
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - minio
  worker:
    build: ../worker
    env_file: .env
    depends_on:
      - db
      - redis
      - minio
  frontend:
    build: ../frontend
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - backend
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: smartagent
      POSTGRES_USER: smart
      POSTGRES_PASSWORD: agent
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data
    ports:
      - "9000:9000"
