name: 🔥 GUARANTEED BUILD

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Setup JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 28
        build-tools: 28.0.3
        
    - name: Install Gradle 6.9.4
      run: |
        wget -q https://services.gradle.org/distributions/gradle-6.9.4-bin.zip
        unzip -q gradle-6.9.4-bin.zip
        echo "$(pwd)/gradle-6.9.4/bin" >> $GITHUB_PATH
        
    - name: Verify Gradle Installation
      run: gradle --version
      
    - name: Build APK Directly
      run: |
        cd simple_app
        gradle assembleDebug --stacktrace
        
    - name: List APK Files
      run: find simple_app -name "*.apk" -type f
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: emergency-smartagent-apk
        path: simple_app/app/build/outputs/apk/debug/app-debug.apk
